=head1 NAME

Gintou - Git repository explorer class

=head1 SYNOPSIS

  use Gintou;

=head1 DESCRIPTION

Gintou is

=head1 AUTHOR

satoshi azuma E<lt>ytnobody at gmail dot comE<gt>

=head1 SEE ALSO

=head1 LICENSE

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
